/**
 * Copyright 2017 Anton Johansson
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.antonjohansson.brmg.core.model;

/**
 * Defines the model generated by the processor.
 */
public class Model
{
    private String detailedReportURL = "";
    private CheckstyleModel checkstyle = new CheckstyleModel();
    private JUnitModel junit = new JUnitModel();

    public String getDetailedReportURL()
    {
        return detailedReportURL;
    }

    public void setDetailedReportURL(String detailedReportURL)
    {
        this.detailedReportURL = detailedReportURL;
    }

    public CheckstyleModel getCheckstyle()
    {
        return checkstyle;
    }

    public void setCheckstyle(CheckstyleModel checkstyle)
    {
        this.checkstyle = checkstyle;
    }

    public JUnitModel getJunit()
    {
        return junit;
    }

    public void setJunit(JUnitModel junit)
    {
        this.junit = junit;
    }
}
