package com.antonjohansson.brmg.core.model;

/**
 * Defines the model generated by the processor.
 */
public class Model
{
    private CheckstyleModel checkstyle = new CheckstyleModel();

    public CheckstyleModel getCheckstyle()
    {
        return checkstyle;
    }

    public void setCheckstyle(CheckstyleModel checkstyle)
    {
        this.checkstyle = checkstyle;
    }
}
